### ISSUE TITLE
Physical quantities behind absorption()  and 'generation.I'

### ISSUE THREAD

**Issue by martinwiemer** [mzszym/oedes#2]
Hallo!

In the photovoltaics steady-state example, to which physical quantities do 'absorption()' and 'generation.I' (part of the loaded standard parameters)  prrecisely refere to?
Could it be the number of absorbed photons per volume element and time, and internal quantum efficiency, respectively?

Thanks a lot!

**Comment by mzszym** [comment]
Generation of charge carriers is only taken into account by generation density, which has SI unit of 1 / (m^3 s). It is a function of position inside the device.
Because often illumination is scaled, DirectGeneration takes position dependent function, which can be called ``absorption(x)``, and also uses scaling parameter such as ``generation.I`` (can be renamed). Their product has unit of 1 / (m^3 s). 
For example, generation(x) could be generation rate at AM1.5 (with unit of 1 / (m^3 s)), and unitless parameter I allows to easily model measurements done with illumination having the same spectrum, but different illumination density. See implementation of ``DirectGeneration.evaluate`` in ``oedes/models/source/simple.py``.
Probably scaling parameter should not be used to model IQE.
